project:
  type: website

website:
  title: "Miscellaneous"
  navbar: 
    background: primary
  page-footer: 
    center:
      - icon: github
        href: https://github.com/camilogarciabotero
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=OJ6452UAAAAJ&hl=en
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-0426-7007
      - icon: twitter
        href: https://twitter.com/gaspardelanoche
      - text: "{{< fa house >}}"
        href: https://camilo-garcia.quarto.pub
  search: 
    location: navbar
  repo-url: https://github.com/camilogarciabotero/blog
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: 
       - flatly
       - style/fonts.scss
      dark: 
        - darkly
        - style/fonts.scss
    code-link: true
    code-copy: hover
    mainfont: Atkinson Hyperlegible
    monofont: JetBrains
    highlight-style: ayu